blogTitle = "Everything Dev and Ops"
subTitle = "Docker, Kubernetes and more"
blogUrl = "http://blog.bonesoul.com"
authorName = "Max Cai"
authorBio = "Written by <strong>Max Cai</strong>  <a href='https://github.com/c4po'>Github</a>"
linkPrefix = ""
gaCode = "UA-90649017-1"
# disqusShortname = "yoursite"
kommentsCode = "f266bc66-1dc4-40a7-9191-e09bd4c2a27b"
