blogTitle = "Everything Dev and Ops"
subTitle = "Docker, Kubernetes and more"
blogUrl = "http://blog.bonesoul.com"
authorName = "Max Cai"
authorBio = "Written by <strong>Max Cai</strong>  <a href='https://github.com/c4po'>Github</a>"
linkPrefix = ""
# gaCode = "UA-0000000-0"
# disqusShortname = "yoursite"
# kommentsCode = "00000000-0000-0000-0000-000000000000"